name: v_ranger
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.7.0
  get: ^4.6.6
  bottom_bar: ^2.0.3
  percent_indicator: ^4.0.1
  flutter_slidable: ^3.1.1
  url_launcher: ^6.3.0
  location: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Black.ttf
          weight: 900
        - asset: assets/fonts/Prompt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Prompt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Prompt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Prompt-Light.ttf
          weight: 300
        - asset: assets/fonts/Prompt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Prompt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Prompt-SemiBold.ttf
          weight: 600
